version: '3'

services:
  instrument_shop:
    image: echocool/comp3030j_software_engineering_project_musical_instrument_shop:${VERSION:-latest}
    container_name: comp3030j_software_engineering_project_musical_instrument_shop
    build:
      context: .
    networks:
      - net
    ports:
      - "8080:8080"
    restart: on-failure
    
  rasa:
    image: echocool/comp3030j_software_engineering_project_musical_instrument_shop_rasa:${VERSION:-latest}
    container_name: comp3030j_software_engineering_project_musical_instrument_shop_rasa
    ports:
      - "5005:5005"
    expose:
      - "5005"
    networks:
      - net
    restart: on-failure


networks:
  net:
